import { getUser } from "@/lib/auth";
import NavbarVoter from "@/components/NavbarVoter";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Voting App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { session, user } = await getUser(); // Tambahkan await untuk fungsi async
  console.log(session);
  console.log(user);

  //   if (!session || !user.role == "VOTER") {
  //     return redirect("/login"); // Tambahkan return setelah redirect
  //   }

  return (
    <>
      <NavbarVoter user={user} />
      <main className="mt-20 px-3">{children}</main>
    </>
  );
}
